# Generated by Django 4.0.5 on 2022-07-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='app',
        ),
    ]
